### ISSUE TITLE
Script is useless if you have MFA installed and a MSOL Module later than 1.1.166.0

### ISSUE THREAD

**Issue by Lucero7919** [noblevarghese/Office365-Users-LastActivityDetails#1]
As MFA is even more prevalent, please update the script to use MFA login rather than tradition Get-Credential cmdlet. This works even if MFA is not enabled for the tenant and is a nicer sign in experience.

Also, the dll library Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll is not available in modules later than 1.1.166.0

**Comment by Taomyn** [comment]
I've hit the same issues as well

**Comment by noblevarghese** [comment]
@Taomyn @Lucero7919 

Thanks for reporting this issue. I have fixed this issue in the new release. Please feel free to use it and let me know in case you run into any other issues. The script now works with the latest MSOnline module installed on the machine. It uses OAuth 2.0 and ADAL for Authentication. Since it uses Modern Authentication, it also supports MFA.
